name: terraform-test

defaults:
  run:
    working-directory: terraform
on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        required: false
        type: number
env:
  AWS_REGION: ap-northeast-1

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
      - name: Terraform init
        run: |
          terraform init --reconfigure
      - name: Terraform plan
        run: |
          terraform plan | tee plan_result.txt
      - name: Terraform apply
        # pull requestに連携時に表示が崩れないように"-no-color" optionをつける
        run: |
          terraform apply -auto-approve | tee apply_result.txt
      - name: Create PR comment
        if: ${{ inputs.pull_request_number }} != null
        run: |
          cat plan_result.txt | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" > plan_result_no_color.txt
          cat apply_result.txt | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" > apply_result_no_color.txt
          gh pr comment ${{ inputs.pull_request_number }} --body-file plan_result_no_color.txt
          gh pr comment ${{ inputs.pull_request_number }} --body-file apply_result_no_color.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
