name: terraform-test

defaults:
  run:
    working-directory: terraform
on:
 workflow_dispatch:
    inputs:
      pull_request_number:
        required: false
        type: number
env:
  AWS_REGION: ap-northeast-1

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
      - name: Terraform init
        run: |
          terraform init --reconfigure
      - name: Terraform plan
        run: |
          terraform plan | tee plan_result.txt
      - name: Terraform apply
        # pull requestに連携時に表示が崩れないように"-no-color" optionをつける
        run: |
          terraform apply -auto-approve | tee apply_result.txt

      - name: Create terraform result with no-color
        if: ${{ inputs.pull_request_number }} != null
        run: |
          cat plan_result.txt | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" >> plan_result_no_color.txt;
          cat apply_result.txt | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" >> apply_result_no_color.txt;

      - name: Create PR file
        if: ${{ inputs.pull_request_number }} != null
        run: |
          echo "## Terraform Plan Result" >> plan_result_for_pr.txt;
            echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> plan_result_for_pr.txt;
          echo "```tf" >> plan_result_for_pr.txt;
          cat plan_result_no_color.txt >> plan_result_for_pr.txt;
          echo "```" >> plan_result_for_pr.txt;

          echo "## Terraform Apply Result" >> apply_result_for_pr.txt;
          readlink -f apply_result_for_pr.txt;
          echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> apply_result_for_pr.txt;
          echo "```tf" >> for_prsult_no_color.txt;
          cat apply_result_no_color.txt >> apply_result_for_pr.txt;
          echo "```" >> apply_result_for_pr.txt;
          gh pr comment ${{ inputs.pull_request_number }} --body-file plan_result_for_pr.txt;
          gh pr comment ${{ inputs.pull_request_number }} --body-file apply_result_for_pr.txt;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
